from __future__ import annotations

from pathlib import Path
from typing import Any

from . import FRAMEWORK_SHORT, __version__, capabilities as capmod
from .config import TrollAppConfig


USAGE_INFO_KEYS = {
    "location": "NSLocationWhenInUseUsageDescription",
    "local_network": "NSLocalNetworkUsageDescription",
    "camera": "NSCameraUsageDescription",
    "microphone": "NSMicrophoneUsageDescription",
    "photos": "NSPhotoLibraryUsageDescription",
    "tracking": "NSUserTrackingUsageDescription",
}


def app_entitlements(cfg: TrollAppConfig) -> dict[str, Any]:
    catalog = capmod.load_catalog()
    blobs = [catalog[cap_id].entitlements for cap_id in cfg.capabilities]
    blobs.append(
        {
            "application-identifier": cfg.bundle_id,
            "com.apple.developer.team-identifier": cfg.team_id,
        }
    )
    blobs.append(cfg.extra_entitlements)
    return capmod.merge_entitlements(blobs)


def tunnel_entitlements(cfg: TrollAppConfig) -> dict[str, Any]:
    catalog = capmod.load_catalog()
    blobs = [catalog[cap_id].tunnel_entitlements for cap_id in cfg.capabilities]
    blobs.append(
        {
            "application-identifier": cfg.packet_tunnel.bundle_id(cfg.bundle_id),
            "com.apple.developer.team-identifier": cfg.team_id,
            "get-task-allow": True,
            "platform-application": True,
            "com.apple.private.security.no-sandbox": True,
            "com.apple.private.security.container-required": False,
            "com.apple.developer.networking.networkextension": ["packet-tunnel-provider"],
        }
    )
    blobs.append(cfg.extra_tunnel_entitlements)
    return capmod.merge_entitlements([blob for blob in blobs if blob])


def info_plist(cfg: TrollAppConfig) -> dict[str, Any]:
    plist: dict[str, Any] = {
        "CFBundleDevelopmentRegion": "$(DEVELOPMENT_LANGUAGE)",
        "CFBundleDisplayName": cfg.display_name,
        "CFBundleExecutable": "$(EXECUTABLE_NAME)",
        "CFBundleIdentifier": "$(PRODUCT_BUNDLE_IDENTIFIER)",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": "$(PRODUCT_NAME)",
        "CFBundlePackageType": "APPL",
        "CFBundleShortVersionString": cfg.version,
        "CFBundleVersion": cfg.build,
        "UILaunchScreen": {},
        "UISupportedInterfaceOrientations": [
            "UIInterfaceOrientationPortrait",
            "UIInterfaceOrientationPortraitUpsideDown",
            "UIInterfaceOrientationLandscapeLeft",
            "UIInterfaceOrientationLandscapeRight",
        ],
        "UISupportedInterfaceOrientations~ipad": [
            "UIInterfaceOrientationPortrait",
            "UIInterfaceOrientationPortraitUpsideDown",
            "UIInterfaceOrientationLandscapeLeft",
            "UIInterfaceOrientationLandscapeRight",
        ],
    }
    if cfg.query_schemes:
        plist["LSApplicationQueriesSchemes"] = list(cfg.query_schemes)
    for usage_key, text in cfg.usage.items():
        plist[USAGE_INFO_KEYS.get(usage_key, usage_key)] = text
    plist.update(cfg.extra_info)
    return plist


def tunnel_info_plist(cfg: TrollAppConfig) -> dict[str, Any]:
    return {
        "CFBundleDevelopmentRegion": "$(DEVELOPMENT_LANGUAGE)",
        "CFBundleDisplayName": cfg.packet_tunnel.display_name,
        "CFBundleExecutable": "$(EXECUTABLE_NAME)",
        "CFBundleIdentifier": "$(PRODUCT_BUNDLE_IDENTIFIER)",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleName": "$(PRODUCT_NAME)",
        "CFBundlePackageType": "XPC!",
        "CFBundleShortVersionString": cfg.version,
        "CFBundleVersion": cfg.build,
        "NSExtension": {
            "NSExtensionPointIdentifier": "com.apple.networkextension.packet-tunnel",
            "NSExtensionPrincipalClass": "$(PRODUCT_MODULE_NAME).PacketTunnelProvider",
        },
    }


def capabilities_swift(cfg: TrollAppConfig) -> str:
    catalog = capmod.load_catalog()
    resolved = set(cfg.capabilities)
    flags = [
        f"    static let {capmod.swift_flag_name(cap_id)} = {_swift_bool(cap_id in resolved)}"
        for cap_id in sorted(catalog)
    ]
    cap_list = ", ".join(f'"{item}"' for item in cfg.capabilities)
    return (
        f"// GENERATED by {FRAMEWORK_SHORT} {__version__}. Do not edit.\n"
        "// Source of truth: trollapp.yml\n\n"
        "enum TADF {\n"
        f'    static let framework = "{FRAMEWORK_SHORT}"\n'
        f'    static let appName = "{_swift_str(cfg.name)}"\n'
        f'    static let displayName = "{_swift_str(cfg.display_name)}"\n'
        f'    static let bundleID = "{_swift_str(cfg.bundle_id)}"\n'
        f'    static let version = "{_swift_str(cfg.version)}"\n'
        f'    static let build = "{_swift_str(cfg.build)}"\n'
        f'    static let channel = "{_swift_str(cfg.channel)}"\n'
        f'    static let minIOS = "{_swift_str(cfg.min_ios)}"\n'
        f"    static let capabilityList: [String] = [{cap_list}]\n"
        + "\n".join(flags)
        + "\n}\n"
    )


def project_yml(cfg: TrollAppConfig) -> str:
    lines = [
        f"# GENERATED by {FRAMEWORK_SHORT} from trollapp.yml. Do not edit.",
        f"name: {cfg.name}",
        "options:",
        f"  bundleIdPrefix: {_bundle_prefix(cfg.bundle_id)}",
        "  deploymentTarget:",
        f'    iOS: "{cfg.min_ios}"',
        "  createIntermediateGroups: true",
        "  developmentLanguage: en",
        "settings:",
        "  base:",
        f"    PRODUCT_BUNDLE_IDENTIFIER: {cfg.bundle_id}",
        f"    PRODUCT_NAME: {cfg.name}",
        f'    MARKETING_VERSION: "{cfg.version}"',
        f'    CURRENT_PROJECT_VERSION: "{cfg.build}"',
        '    TARGETED_DEVICE_FAMILY: "1,2"',
        f'    SWIFT_VERSION: "{cfg.swift_version}"',
        f'    IPHONEOS_DEPLOYMENT_TARGET: "{cfg.min_ios}"',
        "    CODE_SIGN_STYLE: Manual",
        '    CODE_SIGNING_ALLOWED: "NO"',
        '    CODE_SIGNING_REQUIRED: "NO"',
        '    CODE_SIGN_IDENTITY: ""',
        '    DEVELOPMENT_TEAM: ""',
        '    ONLY_ACTIVE_ARCH: "NO"',
        '    SUPPORTS_MACCATALYST: "NO"',
    ]
    if cfg.packages:
        lines.append("packages:")
        lines.extend(_packages_block(cfg))
    lines.append("targets:")
    if cfg.packet_tunnel.enabled:
        lines.extend(_packet_tunnel_target(cfg))
    lines.extend(_app_target(cfg))
    return "\n".join(lines) + "\n"


def _packages_block(cfg: TrollAppConfig) -> list[str]:
    lines: list[str] = []
    for pkg in cfg.packages:
        lines.append(f"  {pkg.name}:")
        if pkg.path:
            lines.append(f"    path: {pkg.path}")
            continue
        lines.append(f"    url: {pkg.url}")
        if pkg.revision:
            lines.append(f"    revision: {pkg.revision}")
        elif pkg.branch:
            lines.append(f"    branch: {pkg.branch}")
        elif pkg.exact:
            lines.append(f'    exactVersion: "{pkg.exact}"')
        else:
            version = pkg.from_version or "1.0.0"
            lines.append(f'    from: "{version}"')
    return lines


def _packet_tunnel_target(cfg: TrollAppConfig) -> list[str]:
    bid = cfg.packet_tunnel.bundle_id(cfg.bundle_id)
    return [
        "  PacketTunnel:",
        "    type: app-extension",
        "    platform: iOS",
        "    sources:",
        "      - path: PacketTunnel",
        "    settings:",
        "      base:",
        f"        PRODUCT_BUNDLE_IDENTIFIER: {bid}",
        "        PRODUCT_NAME: PacketTunnel",
        "        INFOPLIST_FILE: PacketTunnel/Info.plist",
        "        GENERATE_INFOPLIST_FILE: false",
        "        CODE_SIGN_ENTITLEMENTS: PacketTunnel/PacketTunnel.entitlements",
        '        LD_RUNPATH_SEARCH_PATHS: "@executable_path/Frameworks @executable_path/../../Frameworks"',
        '        ENABLE_BITCODE: "NO"',
        '        SKIP_INSTALL: "YES"',
        '        TARGETED_DEVICE_FAMILY: "1,2"',
        "    dependencies:",
        "      - sdk: NetworkExtension.framework",
        "    info:",
        "      path: PacketTunnel/Info.plist",
        "      properties:",
        f"        CFBundleDisplayName: {cfg.packet_tunnel.display_name}",
        "        NSExtension:",
        "          NSExtensionPointIdentifier: com.apple.networkextension.packet-tunnel",
        "          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).PacketTunnelProvider",
    ]


def _app_target(cfg: TrollAppConfig) -> list[str]:
    ldflags = "$(inherited)"
    extra_flags = list(cfg.ldflags)
    if cfg.libraries:
        extra_flags.extend(f"-l{lib}" for lib in cfg.libraries)
    if extra_flags:
        ldflags += " " + " ".join(extra_flags)
    lines = [
        f"  {cfg.name}:",
        "    type: application",
        "    platform: iOS",
        "    sources:",
    ]
    for src in cfg.sources:
        lines.append(f"      - path: {src}")
        if src != "Generated":
            lines.extend(
                [
                    "        excludes:",
                    '          - "**/*.md"',
                    '          - "Info.plist"',
                    '          - "*.entitlements"',
                    '          - "**/*.xcodeproj"',
                    '          - "**/*.xcworkspace"',
                ]
            )
    lines.extend(
        [
            "    settings:",
            "      base:",
            f"        INFOPLIST_FILE: Generated/Info.plist",
            "        GENERATE_INFOPLIST_FILE: false",
            "        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon",
            '        TARGETED_DEVICE_FAMILY: "1,2"',
            '        LD_RUNPATH_SEARCH_PATHS: "@executable_path/Frameworks"',
            '        ENABLE_BITCODE: "NO"',
            f'        OTHER_LDFLAGS: "{ldflags}"',
            f"        CODE_SIGN_ENTITLEMENTS: Generated/{cfg.name}.entitlements",
            '        FRAMEWORK_SEARCH_PATHS: "$(inherited) $(SDKROOT)/System/Library/Frameworks"',
        ]
    )
    if cfg.bridging_header:
        lines.append(f"        SWIFT_OBJC_BRIDGING_HEADER: {cfg.bridging_header}")
    deps: list[str] = []
    if cfg.packet_tunnel.enabled:
        deps.extend(["      - target: PacketTunnel", "        embed: true"])
    for fw in cfg.frameworks:
        sdk = fw if fw.endswith(".framework") else f"{fw}.framework"
        deps.append(f"      - sdk: {sdk}")
    for pkg in cfg.packages:
        for product in pkg.products:
            deps.extend(
                [
                    f"      - package: {pkg.name}",
                    f"        product: {product}",
                ]
            )
    if deps:
        lines.append("    dependencies:")
        lines.extend(deps)
    lines.extend(
        [
            "    info:",
            f"      path: Generated/Info.plist",
            "      properties:",
            f"        CFBundleDisplayName: {cfg.display_name}",
            "        UILaunchScreen: {}",
        ]
    )
    return lines


def _bundle_prefix(bundle_id: str) -> str:
    parts = bundle_id.split(".")
    return ".".join(parts[:-1]) if len(parts) > 1 else bundle_id


def _swift_bool(value: bool) -> str:
    return "true" if value else "false"


def _swift_str(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def write_plist(path: Path, data: dict[str, Any]) -> None:
    import plistlib

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as handle:
        plistlib.dump(data, handle)
